<template>
  <div class="card mb-4" v-bind:class="{vibrate: waiting}">
    <div class="card-body">
      <img class="img-thumbnail"
           v-bind:src="medal.url"
           v-bind:alt="medal.title"
           v-bind:title="medal.title"
      >
      {{medal.title}}
      <button class="btn btn-sm btn-outline-danger"
              @click="remove"
      >
        Remover do jogo
      </button>
    </div>
  </div>
</template>

<script>
  export default {
    name: 'MedalRemove',
    props: {
      g: { // Game
        type: Object,
        required: true
      },
      m: { // Medal
        type: Object,
        required: true
      }
    },
    data() {
      return {
        waiting: false,
        game: {},
        medal: {}
      };
    },
    methods: {
      remove() {
        this.waiting = true;
        this.$auth.$http.delete(`game/${this.game.id}/medal/${this.medal.id}`)
          .then(response => {
            this.$delete(this.game.medals, this.medal.id);
          })
          .catch(error => {
          })
          .finally(() => {
            this.waiting = false;
          });
      }
    },
    mounted() {
      this.game = this.g;
      this.medal = this.m;
    }
  };
</script>

<style lang="scss" scoped>
  @import "~bootstrap/scss/functions";
  @import "../../../assets/styles/variables";
  @import "~bootstrap/scss/variables";
  @import "~bootstrap/scss/mixins";
  @import "~bootstrap/scss/grid";
  @import "~bootstrap/scss/card";
  @import "~bootstrap/scss/buttons";
  @import "~bootstrap/scss/images";
  @import "~bootstrap/scss/utilities/spacing";

  /* ----------------------------------------------
 * Generated by Animista on 2020-3-5 7:34:4
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
   * ----------------------------------------
   * animation vibrate-1
   * ----------------------------------------
   */
  @keyframes vibrate {
    0% {
      transform: translate(0);
    }
    20% {
      transform: translate(-2px, 2px);
    }
    40% {
      transform: translate(-2px, -2px);
    }
    60% {
      transform: translate(2px, 2px);
    }
    80% {
      transform: translate(2px, -2px);
    }
    100% {
      transform: translate(0);
    }
  }

  .vibrate {
    animation: vibrate 0.3s linear infinite both;
  }
</style>
