<template>
  <div class="card mb-4" v-bind:class="{pulsate: waiting}">
    <div class="card-body m-0">
      {{player.name}}
      <div>
        <button class="btn btn-sm btn-outline-success"
                @click="add"
        >
          Adicionar o jogo
        </button>
      </div>
    </div>
  </div>
</template>

<script>
  export default {
    name: 'PlayerAdd',
    props: {
      g: { // Game
        type: Object,
        required: true
      },
      m: { // player
        type: Object,
        required: true
      }
    },
    data() {
      return {
        waiting: false,
        game: {},
        player: {}
      };
    },
    methods: {
      add() {
        this.waiting = true;
        this.$auth.$http.post(`game/${this.game.id}/player`, this.player)
          .then(response => {
            if (response.data) {
              if (response.data.data) {
                const player = response.data.data;
                this.$set(this.game.players, player.id, player);
              }
            }
          })
          .catch(error => {
          })
          .finally(() => {
            this.waiting = false;
          });
      }
    },
    mounted() {
      this.game = this.g;
      this.player = this.m;
    }
  };
</script>

<style lang="scss" scoped>
  @import "~bootstrap/scss/functions";
  @import "../../../assets/styles/variables";
  @import "~bootstrap/scss/variables";
  @import "~bootstrap/scss/mixins";
  @import "~bootstrap/scss/grid";
  @import "~bootstrap/scss/card";
  @import "~bootstrap/scss/buttons";
  @import "~bootstrap/scss/images";
  @import "~bootstrap/scss/utilities/spacing";

  /* ----------------------------------------------
  * Generated by Animista on 2020-3-5 8:25:6
  * Licensed under FreeBSD License.
  * See http://animista.net/license for more info.
  * w: http://animista.net, t: @cssanimista
  * ---------------------------------------------- */

  /**
   * ----------------------------------------
   * animation pulsate-fwd
   * ----------------------------------------
   */

  @keyframes pulsate {
    0% {
      transform: scale(1);
    }
    50% {
      transform: scale(1.02);
    }
    100% {
      transform: scale(1);
    }
  }

  .pulsate {
    -webkit-animation: pulsate 0.5s ease-in-out infinite both;
    animation: pulsate 0.5s ease-in-out infinite both;
  }
</style>
